routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use App\Http\Controllers\Admin\PictureController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ViewPropertyController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
$idRegex = '[0-9]+';
$slugRegex = '[0-9a-z\-]+';
Route::get('/', [HomeController::class, 'index']);
Route::get('/biens', [ViewPropertyController::class, 'index'])->name('property.index');
Route::get('/biens/{slug}-{property}', [ViewPropertyController::class, 'show'])->name('property.show')->where([
    'property' => $idRegex,
    'slug' => $slugRegex,
]);

Route::post('/biens/{property}/contact', [ViewPropertyController::class, 'contact'])->name('property.contact')->where([
    'property' => $idRegex,
]);;

Route::post('/login', [AuthController::class, 'doLogin']);
Route::get('/login', [AuthController::class, 'login'])
    ->middleware('guest')
    ->name('login');
Route::delete('/logout', [AuthController::class, 'logout'])
    ->middleware('auth') //on peut pas se déconnecter si on est pas connecté
    ->name('logout');


Route::prefix('admin')->name('admin.')->middleware('auth')->group( function() use ($idRegex) {
    Route::resource('property', PropertyController::class)->except(['show']);
    Route::resource('option', OptionController::class)->except(['show']);
    Route::delete('picture/{picture}', [PictureController::class, 'destroy'])->name('picture.destroy')
    ->where(['picture' => $idRegex])
    ->can('delete', 'picture');
});

Route::get('/images/{path}', [PictureController::class, 'show'])->where('path', '.*');

app/Models/Property.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;
use App\Models\Option;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Property extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'description',
        'surface',
        'rooms',
        'bedrooms',
        'floor',
        'price',
        'city',
        'adress',
        'postal_code',
        'sold',
    ];

    public function options(): BelongsToMany {
        return $this->belongsToMany(Option::class);
    }

    public function getSlug(): string {
        return Str::slug($this->title);
    }

    public function pictures(): HasMany {
        return $this->hasMany(Picture::class);
    }

/**          
 *   @param UploadedFile[] $files
 */
    public function attachFiles(array $files) {
        $pictures = [];
        foreach($files as $file) {
            if($file->getError()) {
                continue;
            }

            $filename = $file->store('properties/' . $this->id, 'public');
            $pictures[] = [
                'filename' => $filename
            ];
        }

        if(count($pictures) > 0) {
            $this->pictures()->createMany($pictures);
        }
    }

    public function getPicture(): ?Picture {
        return $this->pictures[0] ?? null;
    }

    public function scopeAvailable(Builder $builder): Builder {
        return $builder->where('sold', false);
    }

    public function scopeRecent(Builder $builder): Builder {
        return $builder->orderBy('created_at', 'desc');
    }




}

app/Http/Controllers/Admin/PropertyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\PropertyFormRequest;
use App\Models\Option;
use App\Models\Picture;
use Illuminate\Auth\AuthManager;
use Illuminate\Http\Request;
use App\Models\Property;

class PropertyController extends Controller
{

    //Cas d'une policy sur un controller resource
    /* public function __construct() {
        $this->authorizeResource(Property::class, 'property');
    } */
    /**
     * Display a listing of the resource.
     */
    public function index(AuthManager $authManager)
    {
        //dd($authManager->user()); //injection de dépendance
        return view('admin.properties.index', [
            'properties' => Property::orderBy('created_at', 'desc')->paginate(25)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {   $property = new Property();
        $property->fill([
            'surface' => 40,
            'description' => 'Vous pouvez agrandir la zone d\'écriture en bas à droite',
        ]);
        
        return view('admin.properties.form', [
            'property' => $property,
            'options' => Option::pluck('name', 'id'),
        ]);

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(PropertyFormRequest $request)
    {
        $property = Property::create($request->validated());
        $property->options()->sync($request->validated('options'));
        $property->attachFiles($request->validated('pictures'));
        return to_route('admin.property.index')->with('success', 'Le bien a été crée');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Property $property)
    {
        $this->authorize('delete', $property);
        return view('admin.properties.form', [
            'property' => $property,
            'options' => Option::pluck('name', 'id'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(PropertyFormRequest $request, Property $property)
    {
        $property->update($request->validated());
        $property->options()->sync($request->validated('options'));
        $property->attachFiles($request->validated('pictures'));
        return to_route('admin.property.index')->with('success', 'Le bien a été modifié');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Property $property)
    {
        Picture::destroy($property->pictures()->pluck('id'));
        $property->delete();
        
        return to_route('admin.property.index')->with('success', 'Le bien a été supprimé');

    }
}

app/Http/Controllers/Api/PropertyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\PropertyCollection;
use App\Http\Resources\PropertyResource;
use App\Models\Property;
use Illuminate\Http\Request;

class PropertyController extends Controller
{
    public function index() {
        return PropertyResource::collection(Property::limit(5)->get());
        //return new PropertyCollection(Property::limit(5)->get());
        //return new PropertyResource(Property::find(1)):
    }
}

resources/views/admin/properties/form.blade.php
@extends('admin.admin')

@section('title', $property->exists ? 'Editer un bien' : 'Créer un bien')


@section('content')

<h1>@yield('title')</h1>

<form class="" action="{{ route($property->exists ? 'admin.property.update' : 'admin.property.store', ['property' => $property]) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method($property->exists ? 'put' : 'post')

    <div class="row">
        <div class="col vstack gap-2" style="flex: 100">


            <div class="row">
                @include('shared.input', ['class' => 'col', 'label' => 'Titre', 'name' => 'title', 'value' => $property->title])
                
                <div class="col row">
                    @include('shared.input', ['class' => 'col', 'label' => 'Surface', 'name' => 'surface', 'value' => $property->surface])
                    @include('shared.input', ['class' => 'col', 'label' => 'Prix', 'name' => 'price', 'value' => $property->price])
                    
                </div>
            </div>
            
            @include('shared.input', ['class' => 'col', 'type' => 'textarea', 'label' => 'decription', 'name' => 'description', 'value' => $property->description])
            
            <div class="row">
                @include('shared.input', ['class' => 'col', 'label' => 'Pièces', 'name' => 'rooms', 'value' => $property->rooms])
                @include('shared.input', ['class' => 'col', 'label' => 'Chambres', 'name' => 'bedrooms', 'value' => $property->bedrooms])
                @include('shared.input', ['class' => 'col', 'label' => 'Etage', 'name' => 'floor', 'value' => $property->floor])
            </div>

            <div class="row">
                @include('shared.input', ['class' => 'col', 'label' => 'Adresse', 'name' => 'adress', 'value' => $property->adress])
                @include('shared.input', ['class' => 'col', 'label' => 'Ville', 'name' => 'city', 'value' => $property->city])
                @include('shared.input', ['class' => 'col', 'label' => 'Code postal', 'name' => 'postal_code', 'value' => $property->postal_code])
            </div>

            @include('shared.select', ['label' => 'Options', 'name' => 'options', 'value' => $property->options()->pluck('id'), 'multiple' => true])
            @include('shared.checkbox', ['label' => 'Vendu', 'name' => 'sold', 'value' => $property->sold, 'options' => $options ])
            <div>
                <button class="btn btn-primary">
                    @if ($property->exists)
                        Modifier
                    @else
                        Créer
                    @endif
                </button>
            </div>
        
        </div>

        <div class="col vstack gap-3" style="flex: 25">
            @foreach ($property->pictures as $picture)
            <div id="picture{{ $picture->id }}" class="position-relative">
                <img src="{{ $picture->getImageUrl() }}" alt="images du bien" class="w-100 d-block">
                <button type="button" 
                    class="btn btn-danger position-absolute bottom-0 w-100 start-0"
                    hx-delete="{{ route('admin.picture.destroy', $picture)}}"
                    hx-target="#picture{{ $picture->id }}"
                    hx-swap="delete">
                    <span class="htmx-indicator spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Supprimer
                </button>
            </div>
            @endforeach
            @include('shared.upload', ['label' => 'Images', 'name' => 'pictures', 'multiple' => true])

        </div>
    </div>

    


</form>

@endsection

resources/views/admin/properties/index.blade.php
@extends('admin.admin')


@section('title')
    Les biens
@endsection


@section('content')
<div class="d-flex justify-content-between align-items-center">
    <h1>@yield('title')</h1>
    <a href="{{ route('admin.property.create')}}" class="btn btn-primary">Ajouter un bien</a>
</div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Surface</th>
                <th>Prix</th>
                <th>Ville</th>
                <th class="text-end">Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($properties as $property )
            <tr>
                <td>{{ $property->title }}</td>
                <td>{{ $property->surface }}</td>
                <td>{{ number_format($property->price, thousands_separator: ' ') }}</td>
                <td>{{ $property->city }}</td>
                <td>
                    <div class="d-flex gap-2 w-100 justify-content-end">
                        <a href="{{ route('admin.property.edit', $property) }}" class="btn btn-primary">Editer</a>
                        @can('delete', $property)
                            <form action="{{ route('admin.property.destroy', $property)}}" method="post">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger">Supprimer</button>
                            </form>
                        @endcan
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{ $properties->links() }}


@endsection